# SorcererSpells - List of D&D Spells[SpellModel] for Sorcerer
# Copyright (C) 2011  Cody Garrett, Josh Murphy, and Matt Ingram

# This file is part of FishTornado D&D Character Generator.

# FishTornado D&D Character Generator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# FishTornado D&D Character Generator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with FishTornado D&D Character Generator.  If not, see <http://www.gnu.org/licenses/>.

SpellList.load_spells("0", "Sorcerer", [
["Resistance", "", "PH p272", "Subject gains +1 resistance bonus on all saving throws."],
["Acid Splash", "", "PH p196", "Orb deals 1d3 damage."],
["Detect Poison", "", "PH p219", "Detects poison in one creature or small object."],
["Detect Magic", "", "PH p219", "Detects spells and magic items within 60'."],
["Read Magic", "", "PH p269", "Reads scrolls and spellbooks."],
["Daze", "", "PH p217", "Humanoid creature of 4HD or less loses next action."],
["Dancing Lights", "", "PH p216", "Creates torches or other lights."],
["Flare", "", "PH p232", "Dazzles one creature (-1 on attack rolls)."],
["Light", "", "PH p248", "Object shines like a torch."],
["Ray of Frost", "", "PH p269", "Ray deals 1d3 Cold damage."],
["Ghost Sound", "", "PH p235", "Figment sounds."],
["Disrupt Undead", "", "PH p223", "Deals 1d6 damage to one undead."],
["Touch of Fatigue", "", "PH p294", "Touch attack fatigues target."],
["Mage Hand", "", "PH p249", "5 pound telekinesis."],
["Mending", "", "PH p253", "Makes minor repairs on an object."],
["Message", "", "PH p253", "Whispered conversation at distance."],
["Open/Close", "", "PH p258", "Opens or closes small or light things."],
["Arcane Mark", "", "PH p201", "Inscribes a personal rune (visible or invisible)."],
["Prestidigitation", "", "PH p264", "Performs minor tricks"]])

SpellList.load_spells("1", "Sorcerer", [
["Alarm", "", "PH p197", "Wards an area for 2 hours per level."],
["Endure Elements", "", "PH p226", "Exist comfortably in hot or cold environments."],
["Hold Portal", "", "PH p241", "Holds one door shut."],
["Protection from Chaos", "", "PH p266", "+2 bonus to AC & saves against chaos, counters mind control, & hedges out elementals & outsiders."],
["Protection from Evil", "", "PH p266", "+2 bonus to AC & saves against evil, counters mind control, & hedges out elementals & outsiders."],
["Protection from Good", "", "PH p266", "+2 bonus to AC & saves against good, counters mind control, & hedges out elementals & outsiders."],
["Protection from Law", "", "PH p266", "+2 bonus to AC & saves against law, counters mind control, & hedges out elementals & outsiders."],
["Shield", "", "PH p278", "Invisible disc gives +4 Shield bonus to AC and blocks Magic Missiles."],
["Grease", "", "PH p237", "Makes 10' square or 1 object slippery."],
["Mage Armor", "", "PH p249", "Gives subject +4 armor bonus."],
["Mount", "", "PH p256", "Summons riding horse for 2 hours per level."],
["Obscuring Mist", "", "PH p258", "Fog surrounds you."],
["Summon Monster I", "", "PH p285", "Summons an extraplanar creature to fight for you."],
["Unseen Servant", "", "PH p297", "Invisible force obeys your commands."],
["Comprehend Languages", "", "PH p212", "You understand all spoken and written languages."],
["Detect Secret Doors", "", "PH p220", "Reveals hidden doors within 60'."],
["Detect Undead", "", "PH p220", "Reveals undead within 60'."],
["Identify", "", "PH p243", "Determines properties of a magic item."],
["True Strike", "", "PH p296", "Add +20 insight bonus to your next attack roll."],
["Charm Person", "", "PH p209", "Make one person your friend."],
["Hypnotism", "", "PH p242", "Fascinates 2d4 HD of creatures."],
["Sleep", "", "PH p280", "Puts 4HD of creatures into magical slumber."],
["Burning Hands", "", "PH p207", "1d4 fire damage per level (max 5d4)."],
["Shocking Grasp", "", "PH p279", "Touch delivers 1d6 per level (max 5d6) of electricity damage."],
["Tenser's Floating Disk", "", "PH p294", "3' diameter horizontal disk that holds 100 pounds per level."],
["Color Spray", "", "PH p210", "Knocks unconscious, blinds, or stuns weak creatures."],
["Disguise Self", "", "PH p222", "Changes your appearance."],
["Nystul's Magic Aura", "", "PH p257", "Alters object's magic aura."],
["Silent Image", "", "PH p279", "Creates a minor illusion of your design."],
["Ventriloquism", "", "PH p298", "Throws voice for 1 minute per level."],
["Cause Fear", "", "PH p208", "One creature of 5HD or less flees for 1d4 rounds."],
["Chill Touch", "", "PH p209", "1 touch per level deals 1d6 damage and possibly 1 Strength damage."],
["Ray of Enfeeblement", "", "PH p260", "Ray reduces Strength by 1d6 points +1 per 2 levels (max +5)."],
["Animate Rope", "", "PH p199", "Makes a rope move at your command."],
["Enlarge Person", "", "PH p226", "Humanoid creature doubles in size."],
["Erase", "", "PH p227", "Mundane or magical writing vanishes."],
["Expeditious Retreat", "", "PH p228", "Your land speed increases by 30'."],
["Feather Fall", "", "PH p229", "Objects or creatures fall slowly."],
["Jump", "", "PH p246", "Subject gains bonus on Jump checks."],
["Magic Weapon", "", "PH p251", "Weapon gains +1 enhancement bonus."],
["Reduce Person", "", "PH p269", "Humanoid creature is halved in size."]])

SpellList.load_spells("2", "Sorcerer", [
["Arcane Lock", "", "PH p200", "Magically locks a portal or chest."],
["Obscure Object", "", "PH p258", "Masks object against scrying."],
["Protection from Arrows", "", "PH p266", "Subject immune to most ranged attacks."],
["Resist Energy", "", "PH p246", "Ignores the first 10 (or more) points of damage per attack from a specified energy type."],
["Fog Cloud", "", "PH p232", "Fog obscures vision."],
["Glitterdust", "", "PH p236", "Blinds creatures, outlines invisible creatures."],
["Melf's Acid Arrow", "", "PH p253", "Ranged touch attack; 2d4 acid damage for 1 round + 1 round per 3 levels (7 rounds max)."],
["Summon Monster II", "", "PH p286", "Summons an extraplanar creature to fight for you."],
["Summon Swarm", "", "PH p289", "Summons a swarm of bats, rats, or spiders."],
["Web", "", "PH p301", "Fills 20' radius spread with sticky spider webs."],
["Detect Thoughts", "", "PH p220", "Allows 'listening' to surface thoughts."],
["Locate Object", "", "PH p249", "Senses direction toward object (specific or type)."],
["See Invisibility", "", "PH p275", "Reveals invisible creatures or objects."],
["Daze Monster", "", "PH p217", "Living creature up to 6HD or less looses next action."],
["Tasha's Hideous Laughter", "", "PH p292", "Subject loses actions for 1 round per level."],
["Touch of Idiocy", "", "PH p294", "Subject takes 1d6 Intelligence, Wisdom & Charisma damage."],
["Continual Flame", "", "PH p213", "Makes a permanent, heatless torch."],
["Darkness", "", "PH p216", "20' radius of supernatural shadow."],
["Flaming Sphere", "", "PH p232", "Creates a ball of fire, 2d6 damage, lasts 1 round per level."],
["Gust of Wind", "", "PH p238", "Blows away or knocks down smaller creatures."],
["Scorching Ray", "", "PH p274", "Ranged touch attack, deals 4d6 fire damage, +1 ray/4 levels (max 3)."],
["Shatter", "", "PH p278", "Sonic vibration damages objects or crystalline creatures."],
["Blur", "", "PH p206", "Attacks miss subject 20% of the time."],
["Hypnotic Pattern", "", "PH p242", "Fascinates (2d4 + level) HD of creatures."],
["Invisibility", "", "PH p245", "Subject is invisible for 1 minute per level or until it attacks."],
["Leomund's Trap", "", "PH p247", "Makes one item seem trapped."],
["Magic Mouth", "", "PH p251", "Speaks once when triggered."],
["Minor Image", "", "PH p254", "As Silent Image, plus some sound."],
["Mirror Image", "", "PH p254", "Creates decoy duplicates of you (1d4 + 1 per three levels (max 8))."],
["Misdirection", "", "PH p254", "Misleads divinations for one creature or object."],
["Blindness/Deafness", "", "PH p206", "Makes subject blind or deaf."],
["Command Undead", "", "PH p211", "An undead creature obeys your commands."],
["False Life", "", "PH p229", "Gain 1d10 +1 per level (max +10) temporary hit points."],
["Ghoul Touch", "", "PH p235", "Paralyzes one subject, who exudes stench that sickens those nearby."],
["Scare", "", "PH p274", "Panics creatures up to 5HD."],
["Spectral Hand", "", "PH p282", "Creates disembodied glowing hand to deliver touch attacks."],
["Alter Self", "", "PH p197", "Assume the form of a similar creature."],
["Bear's Endurance", "", "PH p203", "Subject gains +4 Constitution for 1 minute per level."],
["Bull's Strength", "", "PH p207", "Subject gains +4 Strength for 1 minute per level."],
["Cat's Grace", "", "PH p208", "Subject gains +4 Dexterity for 1 minute per level."],
["Darkvision", "", "PH p216", "See 60' in total darkness."],
["Eagle's Splendor", "", "PH p225", "Subject gains +4 Charisma for 1 minute per level."],
["Fox's Cunning", "", "PH p233", "Subject gains +4 Intelligence for 1 minute per level."],
["Knock", "", "PH p246", "Opens locked or magically sealed door."],
["Levitate", "", "PH p248", "Subject moves up and down at your direction."],
["Owl's Wisdom", "", "PH p259", "Subject gains +4 Wisdom for 1 minute per level."],
["Pyrotechnics", "", "PH p267", "Turns fire into blinding light or choking smoke."],
["Rope Trick", "", "PH p273", "As many as eight creatures hide in an extradimensional space."],
["Spider Climb", "", "PH p283", "Grants ability to walk on walls & ceilings."],
["Whispering Wind", "", "PH p301", "Sends a short message one mile per level."]])

SpellList.load_spells("3", "Sorcerer", [
["Dispel Magic", "", "PH p223", "Cancels magical spells and effects."],
["Explosive Runes", "", "PH p228", "Deals 6d6 damage when read."],
["Magic Circle against Chaos", "", "PH p249", "As Protection from Chaos, but 10' radius and 10 minutes per level."],
["Magic Circle against Evil", "", "PH p249", "As Protection from Evil, but 10' radius and 10 minutes per level."],
["Magic Circle against Good", "", "PH p250", "As Protection from Good, but 10' radius and 10 minutes per level."],
["Magic Circle against Law", "", "PH p250", "As Protection from Law, but 10' radius and 10 minutes per level."],
["Nondetection", "", "PH p257", "Hides subject from divination and scrying."],
["Protection from Energy", "", "PH p266", "Absorb 12 damage per level from one kind of energy."],
["Phantom Steed", "", "PH p260", "Magical horse appears for 1 hour per level."],
["Sepia Snake Sigil", "", "PH p276", "Creates text symbol that immobilizes reader."],
["Sleet Storm", "", "PH p280", "Hampers vision and movement."],
["Stinking Cloud", "", "PH p284", "Nauseating vapors, 1 round per level."],
["Summon Monster III", "", "PH p286", "Summons an extraplanar creature to fight for you."],
["Arcane Sight", "", "PH p201", "Magical auras become visible to you."],
["Clairaudience/Clairvoyance", "", "PH p209", "Hear or see at a distance for 1 minute per level."],
["Tongues", "", "PH p294", "Speak any language."],
["Deep Slumber", "", "PH p217", "Puts 10HD of creatures to sleep."],
["Heroism", "", "PH p240", "Gives +2 bonus on attack rolls, saves, skill checks."],
["Hold Person", "", "PH p241", "Paralyzes one person for up to 1 round per level."],
["Rage", "", "PH p268", "Subjects gain +2 to Strength and Constitution, +1 on Will saves, -2 to AC."],
["Suggestion", "", "PH p285", "Compels subject to follow stated course of action."],
["Daylight", "", "PH p216", "60' radius of bright light."],
["Fireball", "", "PH p231", "1d6 fire damage per level, 20' radius."],
["Leomund's Tiny Hut", "", "PH p247", "Creates shelter for ten creatures."],
["Lightning Bolt", "", "PH p248", "Electricity deals 1d6 damage per level."],
["Wind Wall", "", "PH p302", "Deflects arrows, smaller creatures, and gases."],
["Displacement", "", "PH p223", "Attacks miss subject 50% of the time."],
["Illusory Script", "", "PH p243", "Only intended reader can decipher."],
["Invisibility Sphere", "", "PH p245", "Makes everyone within 10' invisible."],
["Major Image", "", "PH p252", "As Silent Image, but sound, smell, and thermal effects."],
["Gentle Repose", "", "PH p234", "Preserves one corpse."],
["Halt Undead", "", "PH p238", "Immobilizes undead for 1 round per level."],
["Ray of Exhaustion", "", "PH p269", "Ray makes subject exhausted."],
["Vampiric Touch", "", "PH p298", "Touch deals 1d6 per 2caster levels; caster gains damage as hit points."],
["Blink", "", "PH p206", "You randomly vanish and reappear for 1 round per level."],
["Flame Arrow", "", "PH p231", "Arrows deal +1d6 fire."],
["Fly", "", "PH p232", "Subject flies at a speed of 60'."],
["Gaseous Form", "", "PH p234", "Subject becomes insubstantial and can fly slowly."],
["Haste", "", "PH p239", "One creature per level moves faster, +1 on attack rolls, AC, and Reflex saves."],
["Keen Edge", "", "PH p245", "Doubles normal weapon's threat range."],
["Magic Weapon, Greater", "", "PH p251", "+1 bonus per four levels (max +5)."],
["Secret Page", "", "PH p275", "Changes one page to hide its real contents."],
["Shrink Item", "", "PH p279", "Object shrinks to 1/16th its normal size."],
["Siphon(DR338 p78", "Drains charges from Wands or Staffs to replace expended spells."],
["Water Breathing", "", "PH p300", "Subject can breathe underwater."]])

SpellList.load_spells("4", "Sorcerer", [
["Dimensional Anchor", "", "PH p221", "Bars extradimensional movement."],
["Fire Trap", "", "PH p231", "Opened object deals 1d4 + 1 per level fire damage."],
["Globe of Invulnerability, Lesser", "", "PH p236", "Stops 1st - 3rd level spell effects."],
["Remove Curse", "", "PH p270", "Frees person or object from a curse."],
["Stoneskin", "", "PH p284", "Ignore 10 points of damage per attack."],
["Dimension Door", "", "PH p221", "Teleports you a short distance."],
["Evard's Black Tentacles", "", "PH p228", "Tentacles grapple all within a 15' spread."],
["Leomund's Secure Shelter", "", "PH p247", "Creates study cottage."],
["Minor Creation", "", "PH p253", "Creates one cloth or wood object."],
["Solid Fog", "", "PH p281", "Blocks vision and slows movement."],
["Summon Monster IV", "", "PH p286", "Calls an extraplanar creature to fight for you."],
["Arcane Eye", "", "PH p200", "Invisible floating eye moves 30' per round."],
["Detect Scrying", "", "PH p219", "Alerts you to magical eavesdropping."],
["Locate Creature", "", "PH p249", "Indicates direction to familiar creature."],
["Scrying", "", "PH p274", "Spies on subject from a distance."],
["Charm Monster", "", "PH p209", "Makes monster believe it is your ally."],
["Confusion", "", "PH p212", "Makes subject behave oddly for 1 round per level."],
["Crushing Despair", "", "PH p215", "Subjects take -2 on attack rolls, damage rolls, saves, and checks."],
["Geas, Lesser", "", "PH p235", "Commands subject of 7 HD or less."],
["Fire Shield", "", "PH p230", "Creatures attacking you take 1d6 + 1 per level damage (fire damage for a Warm Shield, cold damage for a Chill Shield); you are protected from cold (in the case of a Warm Shield) or heat (in the case of a Chill Shield)."],
["Ice Storm", "", "PH p243", "Hail deals 5d6 damage in cylinder 40' across."],
["Otiluke's Resilient Sphere", "", "PH p258", "Force globe protects but traps one subject."],
["Shout", "", "PH p279", "Deafens all within cone and deals 5d6 damage."],
["Wall of Fire", "", "PH p298", "Deals 2d4 fire damage out to 10' and 1d4 out to 20'. Passing through wall deals 2d6 + 1 per level."],
["Wall of Ice", "", "PH p299", "Creates either an ice plane with 15 hp + 1 per level, or a hemisphere which can trap creatures inside."],
["Hallucinatory Terrain", "", "PH p238", "Makes one type of terrain appear like another (field into forest, or the like)."],
["Illusory Wall", "", "PH p243", "Wall, floor, or ceiling looks real, but anything can pass through."],
["Invisibility, Greater", "", "PH p245", "As Invisibility, but subject can attack and stay invisible."],
["Phantasmal Killer", "", "PH p260", "Fearsome illusion kill subject or deals 3d6 damage."],
["Rainbow Pattern", "", "PH p268", "Lights fascinate 24 HD of creatures."],
["Shadow Conjuration", "", "PH p276", "Mimics conjuring below 4th level, but only 20% real."],
["Animate Dead", "", "PH p198", "Creates undead skeletons and zombies."],
["Bestow Curse", "", "PH p203", "Subject either receives a -6 on one ability; -4 penalty on attacks, saves, and skill checks; or 50% chance of losing each action."],
["Contagion", "", "PH p213", "Infects subject with chosen disease."],
["Enervation", "", "PH p226", "Subject gains 1d4 negative levels."],
["Fear", "", "PH p229", "Subjects within cone flee for 1 round per level."],
["Enlarge Person, Mass", "", "PH p226", "Enlarges several creatures."],
["Polymorph", "", "PH p263", "Gives one willing subject a new form."],
#["Rary's Mnemonic Enhancer", "", "PH p268", "Prepares extra spells or retains one just cast. Wizards only"],                #!!!!! NOTE THIS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
["Reduce Person, Mass(PH p269", "Reduces several creatures."],
["Stone Shape", "", "PH p284", "", "Sculpts stone into any shape."]])

SpellList.load_spells("5", "Sorcerer", [
["Break Enchantment", "", "PH p207", "Frees subject fromenchantments, alterations, curses, and petrifaction."],
["Dismissal", "", "PH p222", "Forces a creature to return to native plane."],
["Mordenkainen's Private Sanctum", "", "PH p256", "Prevents anyone from viewing or scrying an area for 24 hours."],
["Cloudkill", "", "PH p210", "Kills up to 3 HD; 4-6 HD save or die; 6+ HD take Constitution damage."],
["Leomund's Secret Chest", "", "PH p247", "Hides expensive chest on Ethereal Plane; you retrieve it at will."],
["Major Creation", "", "PH p252", "As Minor Creation, plus stone and metal."],
["Mordenkainen's Faithful Hound", "", "PH p255", "Phantom dog can guard, attack."],
["Planar Binding, Lesser", "", "PH p261", "Traps an extraplanar creature of 6 HD or less until it performs a task."],
["Summon Monster V", "", "PH p287", "Summons an extraplanar creature to fight for you."],
["Teleport", "", "PH p292", "Instantly transports you as far as 100 miles per level."],
["Wall of Stone", "", "PH p299", "Creates a stone wall that can be shaped."],
["Contact Other Plane", "", "PH p212", "Lets you ask question of an extraplanar entity."],
["Prying Eyes", "", "PH p267", "1d4 floating eyes + 1 per level scout for you."],
["Rary's Telepathic Bond", "", "PH p268", "Link lets allies communicate."],
["Dominate Person", "", "PH p224", "Controls humanoid telepathically."],
["Feeblemind", "", "PH p229", "Subject's Intelligence and Charisma drop to 1."],
["Hold Monster", "", "PH p241", "As Hold Person, but can effect any creature."],
["Mind Fog", "", "PH p253", "Subjects in fog get a -10 on Will saves & Wisdom checks."],
["Symbol of Sleep", "", "PH p291", "Triggered rune puts nearby creatures into a catatonic slumber."],
["Bigby's Interposing Hand", "", "PH p204", "Hand provides cover against one opponent."],
["Cone of Cold", "", "PH p212", "1d6 cold damage per level (max 15d6)."],
["Sending", "", "PH p275", "Delivers a short message anywhere, instantly."],
["Wall of Force", "", "PH p298", "Wall is immune to damage."],
["Dream", "", "PH p225", "Sends message to anyone sleeping."],
["False Vision", "", "PH p229", "Fools scrying with an illusion."],
["Mirage Arcana", "", "PH p254", "As Hallucinatory Terrain, plus structures."],
["Nightmare", "", "PH p257", "Send vision dealing 1d10 damage, fatigue."],
["Persistent Image", "", "PH p260", "As Major Image, but no concentration required."],
["Seeming", "", "PH p275", "Changes the appearance of one person per two levels."],
["Shadow Evocation", "", "PH p277", "Mimics evocation of lower than 5th level, but only 20% real."],
["Blight", "", "PH p206", "Withers one plant or deals 1d6 per level damage to a plant creature."],
["Magic Jar", "", "PH p250", "Enables possession of another creature."],
["Symbol of Pain", "", "PH p290", "Triggered rune wracks nearby creatures with pain."],
["Wave of Fatigue", "", "PH p301", "Several targets become fatigued."],
["Animal Growth", "", "PH p198", "One animal per two levels doubles in size."],
["Baleful Polymorph", "", "PH p202", "Transforms subject into a harmless animal."],
["Fabricate", "", "PH p229", "Transforms raw materials into finished items."],
["Overland Flight", "", "PH p259", "You fly at a speed of 40' and can 'hustle' over long distances."],
["Passwall", "", "PH p259", "Creates a passage through wood or stone walls."],
["Telekinesis", "", "PH p292", "Moves object, attacks creature, or hurls object or creature."],
["Transmute Mud to Rock", "", "PH p295", "Transforms two 10' cubes per level."],
["Transmute Rock to Mud", "", "PH p295", "Transforms two 10' cubes per level."],
["Permanency", "", "PH p259", "Makes certain spells permanent."]])

SpellList.load_spells("6", "Sorcerer", [
["Antimagic Field", "", "PH p200", "Negates magic within 10'."],
["Dispel Magic, Greater", "", "PH p210", "As Dispel Magic, but up to +20 on the check."],
["Globe of Invulnerability", "", "PH p236", "As Lesser Globe of Invulnerability, plus 4th level spell effects."],
["Guards and Wards", "", "PH p237", "Array of magic effects protect area."],
["Repulsion", "", "PH p271", "Creatures can't approach you."],
["Acid Fog", "", "PH p196", "Fog deals acid damage."],
["Planar Binding", "", "PH p261", "As Lesser Planar Binding, but up to 12 HD."],
["Summon Monster VI", "", "PH p287", "Summons an extraplanar creature to fight for you."],
["Wall of Iron", "", "PH p299", "30 hp per 4 levels; can topple onto foes."],
["Analyze Dweomer", "", "PH p197", "Reveals magical aspects of subject."],
["Legend Lore", "", "PH p246", "Lets you learn tales about a person, place, or thing."],
["True Seeing", "", "PH p296", "See all things as they really are."],
["Geas/Quest", "", "PH p234", "As Lesser Geas, plus it affects any creature."],
["Heroism, Greater", "", "PH p240", "Gives a +4 on attack rolls, saves, & skill checks; immunity to fear; temporary hp."],
["Suggestion, Mass", "", "PH p285", "As Suggestion, plus one subject per level."],
["Symbol of Persuasion", "", "PH p290", "Triggered rune charms nearby creatures."],
["Bigby's Forceful Hand", "", "PH p204", "Hand pushes creatures away."],
["Chain Lightning", "", "PH p208", "1d6 damage per level; 1 secondary bolt per level each deal half damage"],
["Contingency", "", "PH p213", "Sets trigger condition for another spell."],
["Otiluke's Freezing Sphere", "", "PH p258", "Freezes water or deals cold damage."],
["Mislead", "", "PH p255", "Turns you invisible and creates illusory double."],
["Permanent Image", "", "PH p260", "Includes sight, sound, and smell."],
["Programmed Image", "", "PH p265", "As Major Image, plus triggered by an event."],
["Shadow Walk", "", "PH p277", "Step into shadow to travel rapidly."],
["Veil", "", "PH p298", "Changes appearance of group of creatures."],
["Circle of Death", "", "PH p209", "Kills 1d4 HD per level of creatures."],
["Create Undead", "", "PH p215", "Create ghouls, ghasts, mummies, or mohrgs."],
["Eyebite", "", "PH p228", "Target becomes panics, sickened, and comatose."],
["Symbol of Fear", "", "PH p290", "Triggered rune panics nearby creatures."],
["Undeath to Death", "", "PH p297", "Destroys 1d4 per level HD of undead (max 20d4)."],
["Bear's Endurance, Mass", "", "PH p203", "As Bear's Endurance, affects one subject per level."],
["Bull's Strength, Mass", "", "PH p207", "As Bull's Strength, affects one subject per level."],
["Cat's Grace, Mass", "", "PH p208", "As Cat's Grace, affects one subject per level."],
["Control Water", "", "PH p214", "Raises, lowers bodies of water."],
["Disintegrate", "", "PH p222", "Makes one creature or object vanish."],
["Eagle's Splendor, Mass", "", "PH p225", "As Eagle's Splendor, affects one subject per level."],
["Flesh to Stone", "", "PH p232", "Turns subject creature into a statue."],
["Fox's Cunning, Mass", "", "PH p233", "As Fox's Cunning, affects one subject per level."],
#["Mordenkainen's Lucubration", "", "PH p256", "Recalls spell of 5th level or lower. Wizards only."],            #!!!!! NOTE THIS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
["Move Earth", "", "PH p257", "Digs trenches and builds hills."],
["Owl's Wisdom, Mass", "", "PH p259", "As Owl's Wisdom, affects one subject per level."],
["Stone to Flesh", "", "PH p285", "Restores a petrified creature."],
["Tenser's Transformation", "", "PH p298", "You gain combat bonuses."]])

SpellList.load_spells("7", "Sorcerer", [
["Banishment", "", "PH p202", "Banishes 2 HD per level of extraplanar creatures."],
["Sequester", "", "PH p276", "Subject is invisible to sight and scrying."],
["Spell Turning", "", "PH p282", "Reflects 1d4+6 spell levels back at caster."],
["Drawmij's Instant Summons", "", "PH p225", "Prepared object appears in your hand."],
["Mordenkainen's Magnificent Mansion", "", "PH p256", "Door leads to extradimensional mansion."],
["Phase Door", "", "PH p261", "Invisible passage through wood or stone."],
["Plane Shift", "", "PH p262", "As many as eight subjects travel to another plane."],
["Summon Monster VII", "", "PH p287", "Summons an extraplanar creature to fight for you."],
["Teleport, Greater", "", "PH p292", "As Teleport, but no range limit and off-target arrival."],
["Teleport Object", "", "PH p293", "As Teleport, but affects a touched object."],
["Arcane Sight, Greater", "", "PH p201", "As Arcane Sight, but also reveals magic effects on creatures and objects."],
["Scrying, Greater", "", "PH p275", "As Scrying, but faster and longer."],
["Vision", "", "PH p298", "As Legend Lore, but quicker and strenuous."],
["Hold Person, Mass", "", "PH p241", "As Hold Person, but all within 30'."],
["Insanity", "", "PH p244", "Subject suffers continuous Confusion."],
["Power Word Blind", "", "PH p263", "Blinds creatures with 200 hp or less."],
["Symbol of Stunning", "", "PH p291", "Triggered rune stuns nearby creatures."],
["Bigby's Grasping Hand", "", "PH p204", "Hand provides cover, pushes, or grapples."],
["Delayed Blast Fireball", "", "PH p217", "1d6 per level fire damage; you can postpone the blast for up to 5 rounds."],
["Forcecage", "", "PH p232", "Cube or cage of force imprisons all inside."],
["Mordenkainen's Sword", "", "PH p256", "Floating magic blade strikes opponents."],
["Prismatic Spray", "", "PH p264", "Rays hit subjects with a variety of effects."],
["Invisibility, Mass", "", "PH p245", "As Invisibility, but affects all in range."],
["Project Image", "", "PH p265", "Illusory double can talk and cast spells."],
["Shadow Conjuration, Greater", "", "PH p276", "As Shadow Conjuration, but up to 6th level spells and 60% real"],
["Simulacrum", "", "PH p279", "Creates partially real double of a creature."],
["Control Undead", "", "PH p214", "Undead don't attack you while under your command."],
["Finger of Death", "", "PH p230", "Kills one subject."],
["Symbol of Weakness", "", "PH p291", "Triggered rune weakens nearby creatures."],
["Waves of Exhaustion", "", "PH p301", "Several targets become exhausted."],
["Control Weather", "", "PH p214", "Changes weather in local area."],
["Ethereal Jaunt", "", "PH p227", "You become ethereal for 1 round per level."],
["Reverse Gravity", "", "PH p273", "Objects and creatures fall upward."],
["Statue", "", "PH p284", "Subject can become a statue at will."],
["Limited Wish", "", "PH p248", "Alters reality, within spell limits."]])

SpellList.load_spells("8", "Sorcerer", [
["Dimensional Lock", "", "PH p221", "Teleportation and interplanar travel are blocked for 1 day per level."],
["Mind Blank", "", "PH p253", "Subject is immune to mental/emotional magic and scrying."],
["Prismatic Wall", "", "PH p264", "Wall's colors have array of effects."],
["Protection from Spells", "", "PH p266", "Confers +8 resistance bonus."],
["Incendiary Cloud", "", "PH p244", "Cloud deals 4d6 fire damage per round."],
["Maze", "", "PH p252", "Traps subject in an extradimensional maze."],
["Planar Binding, Greater", "", "PH p261", "As Lesser Planar Binding, but up to 18 HD."],
["Summon Monster VIII", "", "PH p287", "Summons an extraplanar creature to fight for you."],
["Trap the Soul", "", "PH p296", "Imprisons subject within gem."],
["Discern Location", "", "PH p222", "Reveals the exact location of a creature or object."],
["Moment of Prescience", "", "PH p255", "You gain insight bonus on a single attack roll, check , or save."],
["Prying Eyes, Greater", "", "PH p267", "As Prying Eyes, but eyes have True Seeing."],
["Antipathy", "", "PH p200", "Object of location affect by spell repels certain creatures."],
["Binding", "", "PH p204", "Utilizes an array of techniques to imprison a creature."],
["Charm Monster, Mass", "", "PH p206", "As Charm Monster, but all within 30'."],
["Demand", "", "PH p217", "As Sending, plus you can send Suggestion."],
["Otto's Irresistible Dance", "", "PH p259", "Forces subject to dance."],
["Power Word Stun", "", "PH p263", "Stuns creatures with 150 hp or less."],
["Symbol of Insanity", "", "PH p290", "Triggered rune renders nearby creatures insane."],
["Sympathy", "", "PH p292", "Object or location attracts certain creatures."],
["Bigby's Clenched Fist", "", "PH p203", "Large hand provides cover, pushes, o attacks your foes."],
["Otiluke's Telekinetic Sphere", "", "PH p258", "As Otiluke's Resilient Sphere, but you move the sphere telekinetically."],
["Polar Ray", "", "PH p262", "Ranged touch attack deals 1d6 per level cold damage."],
["Shout, Great", "", "PH p279", "Devastating yell deals 10d6 sonic damage; stuns creatures, damages objects."],
["Sunburst", "", "PH p289", "Blinds all within 10', deals 6d6 damage."],
["Scintillating Pattern", "", "PH p274", "Twisting colors confuse, stun, or render unconscious."],
["Screen", "", "PH p274", "Illusion hides area from vision, scrying."],
["Shadow Evocation, Greater", "", "PH p277", "As Shadow Evocation, but up to 7th level and 60% real."],
["Clone", "", "PH p210", "Duplicate awakens when original dies."],
["Create Greater Undead", "", "PH p215", "Creates shadows, wraiths, spectres, or devourers."],
["Horrid Wilting", "", "PH p242", "Deals 1d6 damage per level within 30'."],
["Symbol of Death", "", "PH p289", "Triggered rune slays nearby creatures."],
["Iron Body", "", "PH p245", "You body becomes living iron."],
["Polymorph Any Object", "", "PH p263", "Changes any subject into anything else."],
["Temporal Stasis", "", "PH p293", "Puts subject into suspended animation."]])

SpellList.load_spells("9", "Sorcerer", [
["Freedom", "", "PH p233", "Releases creature suffering from the spell Imprisonment."],
["Imprisonment", "", "PH p244", "Entombs subject beneath the earth."],
["Mordenkainen's Disjunction", "", "PH p255", "Dispels magic, disenchants magic items."],
["Prismatic Sphere", "", "PH p264", "As Prismatic Wall, but surrounds on all sides."],
["Gate", "", "PH p234", "Connects two planes for travel or summoning."],
["Refuge", "", "PH p270", "Alters item to transport its possessor to you."],
["Summon Monster IX", "", "PH p288", "Summons an extraplanar creature to fight for you."],
["Teleportation Circle", "", "PH p293", "Circle teleports any creature inside to designated spot."],
["Foresight", "", "PH p207", "'Sixth sense' warns of impending danger."],
["Dominate Monster", "", "PH p224", "As Dominate Person, but any creature."],
["Hold Monster, Mass", "", "PH p241", "AS Hold Monster, but all within 30'."],
["Power Word Kill", "", "PH p263", "Kills one creature with 100 hp or less."],
["Bigby's Crushing Hand", "", "PH p203", "Large hand provides cover, pushes, or crushes your foes."],
["Meteor Swarm", "", "PH p253", "Four exploding spheres each deal 6d6 fire damage."],
["Shades", "", "PH p276", "As Shadow Conjuration, but up to 8th level and 80% real."],
["Weird", "", "PH p301", "As Phantasmal Killer, but affects all within 30'."],
["Astral Projection", "", "PH p201", "Projects you and companions into the Astral Plane."],
["Energy Drain", "", "PH p226", "Subject gains 2d4 negative levels."],
["Soul Bind", "", "PH p226", "Traps newly dead soul to prevent Resurrection."],
["Wail of the Banshee", "", "PH p298", "Kills one creature per level."],
["Etherealness", "", "PH p228", "Travel to Ethereal Plane with companions."],
["Shapechange", "", "PH p277", "Transforms you into any creature, and change forms once per round."],
["Time Stop", "", "PH p294", "You act freely for 1d4+1 rounds."],
["Wish", "", "PH p302", "As Limited Wish, but with fewer limits."]])

