
SpellList.load_spells("0", "Bard", [
["Dancing Lights", "Evocation [Light]", "PH p272", "Creates torches or other lights."],
["Daze", "Enchantment (Compulsion) [Mind-Affecting]", "PH p217", "Humanoid creature of 4 HD or less loses next action."],
["Detect Magic", "Divination", "PH p219", "Detects spells and magic items within 60 ft."],
["Flare", "Evocation [Light]", "PH p232", "Dazzles one creature (-1 on attack rolls)."],
["Ghost Sound", "Illusion (Figment)", "PH p235", "Figment sounds."],
["Know Direction", "Divination", "PH p246", "You discern north."],
["Light", "Evocation [Light]", "PH p248", "Object shines like a torch."],
["Lullaby", "Enchantment (Compulsion) [Mind-Affecting]", "PH p249", "Makes subject drowsy; -5 on Spot and Listen checks, -2 on Will saves against sleep."],
["Mage Hand", "Transmutation", "PH p249", "5-pound telekinesis."],
["Mending", "Transmutation", "PH p253", "Makes minor repairs on an object."],
["Message", "Transmutation [Language-Dependent]", "PH p253", "Whispered conversation at distance."],
["Open/Close", "Transmutation", "PH p258", "Opens or closes small or light things."],
["Prestidigitation", "Universal", "PH p264", "Performs minor tricks."],
["Read Magic", "Divination", "PH p269", "Read scrolls and spellbooks."],
["Resistance", "Abjuration", "PH p264", "Subject gains +1 on saving throws."],
["Summon Instrument", "Conjuration (Summoning)", "PH p285", "Summons one instrument of the caster's choice."]])

SpellList.load_spells("1", "Bard", [
["Alarm", "Abjuration", "PH p197", "Wards an area for 2 hours/level."],
["Animate Rope", "Transmutation", "PH p199", "Makes a rope move at your command."],
["Cause Fear", "Necromancy [Fear, Mind-Affecting],", "PH p208", "One creature of 5 HD or less flees for 1d4 rounds."],
["Charm Person", "Enchantment (Charm) [Mind-Affecting],", "PH p209", "Makes one person your friend."],
["Comprehend Languages", "Divination", "PH p212", "You understand all spoken and written languages."],
["Confusion, Lesser", "Enchantment (Compulsion) [Mind-Affecting],", "PH p212", "One creature is confused for 1 round."],
["Cure Light Wounds", "Conjuration (Healing)", "PH p215", "Cures 1d8 damage +1/ level (max +5)."],
["Detect Secret Doors", "Divination", "PH p220", "Reveals hidden doors within 60 ft."],
["Disguise Self", "Illusion (Glamer)", "PH p222", "Changes your appearance."],
["Erase", "Transmutation", "PH p227", "Mundane or magical writing vanishes."],
["Expeditious Retreat", "Transmutation", "PH p228", "Your speed increases by 30 ft."],
["Feather Fall", "Transmutation", "PH p229", "Objects or creatures fall slowly."],
["Grease", "Conjuration (Creation)", "PH p237", "Makes 10-ft. square or one object slippery."],
["Hideous Laughter", "Enchantment (Compulsion) [Mind-Affecting]", "PH p292", "Subject loses actions for 1 round/ level."],
["Hypnotism", "Enchantment (Compulsion) [Mind-Affecting],", "PH p242", "Fascinates 2d4 HD of creatures."],
["Identify", "Divination", "PH p243", "Determines properties of magic item."],
["Magic Mouth", "Illusion (Glamer)", "PH p251", "Speaks once when triggered."],
["Magic Aura", "Illusion (Glamer)", "PH p257", "Alters object's magic aura."],
["Obscure Object", "Abjuration", "PH p258", "Masks object against scrying."],
["Remove Fear", "Abjuration", "PH p271", "Suppresses fear or gives +4 on saves against fear for one subject + one per four levels."],
["Silent Image", "Illusion (Figment)", "PH p279", "Creates minor illusion of your design."],
["Sleep", "Enchantment (Compulsion) [Mind-Affecting],", "PH p280", "Puts 4 HD of creatures into magical slumber."],
["Summon Monster I", "Conjuration (Summoning)", "PH p285", "Calls extraplanar creature to fight for you."],
["Undetectable Alignment", "Abjuration", "PH p297", "Conceals alignment for 24 hours."],
["Unseen Servant", "Conjuration (Creation)", "PH p297", "Invisible force obeys your commands."],
["Ventriloquism", "Illusion (Figment)", "PH p298", "Throws voice for 1 min./ level."]])

SpellList.load_spells("2", "Bard", [
["Alter Self", "Transmutation", "PH p197", "Assume form of a similar creature."],
["Animal Messenger", "Enchantment (Compulsion) [Mind-Affecting],", "PH p198", "Sends a Tiny animal to a specific place."],
["Animal Trance", "Enchantment (Compulsion) [Mind-Affecting, Sonic],", "PH p198", "Fascinates 2d6 HD of animals."],
["Blindness/ Deafness", "Necromancy", "PH p206", "Makes subject blind or deaf."],
["Blur", "Illusion (Glamer)", "PH p206", "Attacks miss subject 20% of the time."],
["Calm Emotions", "Enchantment (Compulsion) [Mind-Affecting],", "PH p207", "Calms creatures, negating emotion effects."],
["Cat's Grace", "Transmutation", "PH p208", "Subject gains +4 to Dex for 1 min./ level."],
["Cure Moderate Wounds", "Conjuration (Healing)", "PH p216", "Cures 2d8 damage +1/ level (max +10)."],
["Darkness", "Evocation [Darkness],", "PH p216", "20-ft. radius of supernatural shadow."],
["Daze Monster", "Enchantment (Compulsion) [Mind-Affecting],", "PH p217", "Living creature of 6 HD or less loses next action."],
["Delay Poison", "Conjuration (Healing)", "PH p217", "Stops poison from harming subject for 1 hour/  level."],
["Detect Thoughts", "Divination [Mind-Affecting],", "PH p220", "Allows 'listening' to surface thoughts."],
["Eagle's Splendor", "Transmutation", "PH p225", "Subject gains +4 to Cha for 1 min./ level."],
["Enthrall", "Enchantment (Charm) [Language Dependent, Mind-Affecting, Sonic],", "PH p227", "Captivates all within 100 ft. + 10 ft./ level."],
["Fox's Cunning", "Transmutation", "PH p233", "Subject gains +4 to Int for 1 min./ level."],
["Glitterdust", "Conjuration (Creation)", "PH p236", "Blinds creatures, outlines invisible creatures."],
["Heroism", "Enchantment (Compulsion) [Mind-Affecting],", "PH p240", "Gives +2 on attack rolls, saves, skill checks."],
["Hold Person", "Enchantment (Compulsion) [Mind-Affecting],", "PH p241", "Paralyzes one humanoid for 1 round/ level."],
["Hypnotic Pattern", "Illusion (Pattern) [Mind-Affecting],", "PH p242", "Fascinates (2d4 + level) HD of creatures."],
["Invisibility", "Illusion (Glamer)", "PH p245", "Subject is invisible for 1 min./ level or until it attacks."],
["Locate Object", "Divination", "PH p249", "Senses direction toward object (specific or type)."],
["Minor Image", "Illusion (Figment)", "PH p254", "As silent image, plus some sound."],
["Mirror Image", "Illusion (Figment)", "PH p254", "Creates decoy duplicates of you (1d4 +1 per three levels, max 8)."],
["Misdirection", "Illusion (Glamer)", "PH p254", "Misleads divinations for one creature or object."],
["Pyrotechnics", "Transmutation", "PH p267", "Turns fire into blinding light or choking smoke."],
["Rage", "Enchantment (Compulsion) [Mind-Affecting],", "PH p268", "Gives +2 to Str and Con, +1 on Will saves, -2 to AC."],
["Scare", "Necromancy [Fear, Mind-Affecting],", "PH p274", "Panics creatures of less than 6 HD."],
["Shatter", "Evocation [Sonic],", "PH p278", "Sonic vibration damages objects or crystalline creatures."],
["Silence", "Illusion (Glamer)", "PH p279", "Negates sound in 20-ft. radius."],
["Sound Burst", "Evocation [Sonic],", "PH p281", "Deals 1d8 sonic damage to subjects; may stun them."],
["Suggestion", "Enchantment (Compulsion) [Language-Dependent, Mind-Affecting],", "PH p285", "Compels subject to follow stated course of action."],
["Summon Monster II", "Conjuration (Summoning)", "PH p286", "Calls extraplanar creature to fight for you."],
["Summon Swarm", "Conjuration (Summoning)", "PH p289", "Summons swarm of bats, rats, or spiders."],
["Tongues", "Divination", "PH p294", "Speak any language."],
["Whispering Wind", "Transmutation [Air]", "PH p201", "Sends a short message 1 mile/ level."]])

SpellList.load_spells("3", "Bard", [
["Blink", "Transmutation", "PH p206", "You randomly vanish and reappear for 1 round/ level."],
["Charm Monster", "Enchantment (Charm) [Mind-Affecting]", "PH p209", "Makes monster believe it is your ally."],
["Clairaudience/ Clairvoyance", "Divination (Scrying)", "PH p209", "Hear or see at a distance for 1 min./ level."],
["Confusion", "Enchantment (Compulsion) [Mind-Affecting]", "PH p212", "Subjects behave oddly for 1 round/ level."],
["Crushing Despair", "Enchantment (Compulsion) [Mind-Affecting]", "PH p215", "Subjects take -2 on attack rolls, damage rolls, saves, and checks."],
["Cure Serious Wounds", "Conjuration (Healing)", "PH p216", "Cures 3d8 damage +1/ level (max +15)."],
["Daylight", "Evocation [Light]", "PH p216", "60-ft. radius of bright light."],
["Deep Slumber", "Enchantment (Compulsion) [Mind-Affecting]", "PH p217", "Puts 10 HD of creatures to sleep."],
["Dispel Magic", "Abjuration", "PH p223", "Cancels magical spells and effects."],
["Displacement", "Illusion (Glamer)", "PH p223", "Attacks miss subject 50%."],
["Fear", "Necromancy [Fear, Mind-Affecting]", "PH p229", "Subjects within cone flee for 1 round/ level."],
["Gaseous Form", "Transmutation", "PH p234", "Subject becomes insubstantial and can fly slowly."],
["Geas, Lesser", "Enchantment (Compulsion) [Language-Dependent, Mind-Affecting]", "PH p235", "Commands subject of 7 HD or less."],
["Glibness", "Transmutation", "PH p235", "You gain +30 bonus on Bluff checks, and your lies can escape magical discernment."],
["Good Hope", "Enchantment (Compulsion) [Mind-Affecting]", "PH p237", "Subjects gain +2 on attack rolls, damage rolls, saves, and checks."],
["Haste", "Transmutation", "PH p239", "One creature/ level moves faster, +1 on attack rolls, AC, and Reflex saves."],
["Illusory Script", "Illusion (Phantasm) [Mind-Affecting]", "PH p243", "Only intended reader can decipher."],
["Invisibility Sphere", "Illusion (Glamer)", "PH p245", "Makes everyone within 10 ft. invisible."],
["Major Image", "Illusion (Figment)", "PH p252", "As silent image, plus sound, smell and thermal effects."],
["Phantom Steed", "Conjuration (Creation)", "PH p260", "Magic horse appears for 1 hour/ level."],
["Remove Curse", "Abjuration", "PH p270", "Frees object or person from curse."],
["Scrying", "Divination (Scrying)", "PH p274", "Spies on subject from a distance."],
["Sculpt Sound", "Transmutation", "PH p275", "Creates new sounds or changes existing ones."],
["Secret Page", "Transmutation", "PH p275", "Changes one page to hide its real content."],
["See Invisibility", "Divination", "PH p275", "Reveals invisible creatures or objects."],
["Sepia Snake Sigil", "Conjuration (Creation) [Force]", "PH p276", "Creates text symbol that immobilizes reader."],
["Slow", "Transmutation", "PH p280", "One subject/ level takes only one action/ round, -1 to AC, reflex saves, and attack rolls."],
["Speak with Animals", "Divination", "PH p281", "You can communicate with animals."],
["Summon Monster III", "Conjuration (Summoning)", "PH p286", "Calls extraplanar creature to fight for you."],
["Tiny Hut", "Evocation [Force]", "PH p247", "Creates shelter for ten creatures."]])

SpellList.load_spells("4", "Bard", [
["Break Enchantment", "Abjuration", " ", "Frees subjects from enchantments, alterations, curses, and petrification."],
["Cure Critical Wounds", "Conjuration (Healing)", " ", "Cures 4d8 damage +1/ level (max +20)."],
["Detect Scrying", "Divination", " ", "Alerts you of magical eavesdropping."],
["Dimension Door", "Conjuration (Teleportation)", " ", "Teleports you short distance."],
["Dominate Person", "Enchantment (Compulsion) [Mind-Affecting]", " ", "Controls humanoid telepathically."],
["Freedom of Movement", "Abjuration", " ", "Subject moves normally despite impediments."],
["Hallucinatory Terrain", "Illusion (Glamer)", " ", "Makes one type of terrain appear like another (field into forest, or the like)."],
["Hold Monster", "Enchantment (Compulsion) [Mind-Affecting]", " ", "As hold person, but any creature."],
["Invisibility, Greater", "Illusion (Glamer)", " ", "As invisibility, but subject can attack and stay invisible."],
["Legend Lore", "Divination", " ", "Lets you learn tales about a person, place, or thing."],
["Locate Creature", "Divination", " ", "Indicates direction to familiar creature."],
["Modify Memory", "Enchantment (Compulsion) [Mind-Affecting]", " ", "Changes 5 minutes of subject's memories."],
["Neutralize Poison", "Conjuration (Healing)", " ", "Immunizes subject against poison, detoxifies venom in or on subject."],
["Rainbow Pattern", "Illusion (Pattern) [Mind-Affecting]", " ", "Lights fascinate 24 HD of creatures."],
["Repel Vermin", "Abjuration", " ", "Insects, spiders, and other vermin stay 10 ft. away."],
["Secure Shelter", "Conjuration (Creation)", " ", "Creates sturdy cottage."],
["Shadow Conjuration", "Illusion (Shadow)", " ", "Mimics conjuring below 4th level, but only 20% real."],
["Shout", "Evocation [Sonic]", " ", "Deafens all within cone and deals 5d6 sonic damage."],
["Speak with Plants", "Divination", " ", "You can talk to normal plants and plant creatures."],
["Summon Monster IV", "Conjuration (Summoning)", " ", "Calls extraplanar creature to fight for you."],
["Zone of Silence", "Illusion (Glamer)", " ", "Keeps eavesdroppers from overhearing conversations."]])

SpellList.load_spells("5", "Bard", [
["Cure Light Wounds, Mass", "Conjuration (Healing)", " ", "Cures 1d8 damage +1/ level for many creatures."],
["Dispel Magic, Greater", "Abjuration", " ", "As dispel magic, but +20 on check."],
["Dream", "Illusion (Phantasm) [Mind-Affecting]", " ", "Sends message to anyone sleeping."],
["False Vision", "Illusion (Glamer)", " ", "Fools scrying with an illusion."],
["Heroism, Greater", "Enchantment (Compulsion) [Mind-Affecting]", " ", "Gives +4 bonus on attack rolls, saves, skill checks; immunity to fear; temporary hp."],
["Mind Fog", "Enchantment (Compulsion) [Mind-Affecting]", " ", "Subjects in fog get -10 to Wis and Will checks."],
["Mirage Arcana", "Illusion (Glamer)", " ", "As hallucinatory terrain, plus structures."],
["Mislead", "Illusion (Figment, Glamer)", " ", "Turns you invisible and creates illusory double."],
["Nightmare", "Illusion (Phantasm) [Mind-Affecting, Evil]", " ", "Sends vision dealing 1d10 damage, fatigue."],
["Persistent Image", "Illusion (Figment)", " ", "As major image, but no concentration required."],
["Seeming", "Illusion (Glamer)", " ", "Changes appearance of one person per two levels."],
["Shadow Evocation", "Illusion (Shadow)", " ", "Mimics evocation of lower than 5th level, but only 20% real."],
["Shadow Walk", " ", "Illusion (Shadow)", "Step into shadow to travel rapidly."],
["Song of Discord", "Enchantment (Compulsion) [Mind-Affecting, Sonic]", " ", "Forces targets to attack each other."],
["Suggestion, Mass", "Enchantment (Compulsion) [Language-Dependent, Mind-Affecting]", " ", "As suggestion, plus one subject/ level."],
["Summon Monster V", "Conjuration (Summoning)", " ", "Calls extraplanar creature to fight for you."]])

SpellList.load_spells("6", "Bard", [
["Analyze Dweomer", "Divination", " ", "Reveals magical aspects of subject."],
["Animate Objects", "Transmutation", " ", "Objects attack your foes."],
["Cat's Grace, Mass", "Transmutation", " ", "As cat's grace, affects one subject/ level."],
["Charm Monster, Mass", "Enchantment (Charm) [Mind-Affecting]", " ", "As charm monster, but all within 30 ft."],
["Cure Moderate Wounds, Mass", "Conjuration (Healing)", " ", "Cures 2d8 damage +1/ level for many creatures."],
["Eagle's Splendor, Mass", "Transmutation", " ", "As eagle's splendor, affects one subject/ level."],
["Eyebite", "Necromancy [Evil]", " ", "Target becomes panicked, sickened, and comatose."],
["Find the Path", "Divination", " ", "Shows most direct way to a location."],
["Fox's Cunning, Mass", "Transmutation", " ", "As fox's cunning, affects one subject/ level."],
["Geas/ Quest", "Enchantment (Compulsion) [Language-Dependent, Mind-Affecting]", " ", "As lesser geas, plus it affects any creature."],
["Heroes' Feast", "Conjuration (Creation)", " ", "Food for one creature/ level cures and grants combat bonuses."],
["Irresistible Dance", "Enchantment (Compulsion) [Mind-Affecting]", " ", "Forces subject to dance."],
["Permanent Image", "Illusion (Figment)", " ", "Includes sight, sound, and smell."],
["Programmed Image", "Illusion (Figment)", " ", "As major image, plus triggered by event."],
["Project Image", "Illusion (Shadow)", " ", "Illusory double can talk and cast spells."],
["Scrying, Greater", "Divination (Scrying)", " ", "As scrying, but faster and longer."],
["Shout, Greater", "Evocation [Sonic]", " ", "Devastating yell deals 10d6 sonic damage; stuns creatures, damages objects."],
["Summon Monster VI", "Conjuration (Summoning) ", " ", "Calls extraplanar creature to fight for you."],
["Sympathetic Vibration", "Evocation [Sonic]", " ", "Deals 2d10 damage/ round to freestanding structure."],
["Veil", "Illusion (Glamer)", " ", "Changes appearance of group of creatures."]])